var gDeviceData = {
    "type": "ui-device",
    "name": "iphone5",
    "w": 765,
    "h": 1600,
    "x": 475,
    "y": -59,
    "text": "",
    "scale": 1,
    "userMovable": true,
    "userResizable": false,
    "textType": 0,
    "vAlign": "middle",
    "hAlign": "center",
    "defWidth": 765,
    "defHeight": 1600,
    "rectSelectable": false,
    "enable": true,
    "visible": true,
    "opacity": 1,
    "vMargin": 0,
    "hMargin": 0,
    "xAttr": 0,
    "yAttr": 0,
    "widthAttr": 0,
    "heightAttr": 0,
    "needRelayout": true,
    "isUIDevice": true,
    "isUIElement": true,
    "hasChildren": true,
    "isContainer": true,
    "textTitle": "Text",
    "isRect": true,
    "xParam": 1,
    "yParam": 1,
    "widthParam": 1,
    "heightParam": 1,
    "style": {
        "lineWidth": 2,
        "lineColor": "Green",
        "fillColor": "Black",
        "textColor": "White",
        "fontSize": 24,
        "fontFamily": "serif"
    },
    "events": {
        "onClick": "console.log(\"onClick was triggered\")"
    },
    "images": {
        "display": 2,
        "default_bg": "drawapp8\/images\/devices\/device_iphone5.png"
    },
    "config": {
        "name": "iphone5",
        "bg": "drawapp8\/images\/devices\/device_iphone5.png",
        "platform": "iphone",
        "version": "5",
        "lcdDensity": "xhdpi",
        "width": 765,
        "height": 1600,
        "screenX": 65,
        "screenY": 238,
        "screenW": 640,
        "screenH": 1136,
        "hasMenuBar": false
    },
    "children": [
        {
            "type": "ui-screen",
            "name": "ui-screen",
            "w": 640,
            "h": 1136,
            "x": 65,
            "y": 238,
            "text": "",
            "scale": 1,
            "userMovable": false,
            "userResizable": false,
            "textType": 0,
            "vAlign": "middle",
            "hAlign": "center",
            "defWidth": 640,
            "defHeight": 960,
            "rectSelectable": true,
            "enable": true,
            "visible": true,
            "opacity": 1,
            "vMargin": 0,
            "hMargin": 0,
            "xAttr": 0,
            "yAttr": 0,
            "widthAttr": 0,
            "heightAttr": 0,
            "needRelayout": true,
            "xParam": 1,
            "yParam": 1,
            "widthParam": 1,
            "heightParam": 1,
            "hasStatusBar": true,
            "yStatusBar": 0,
            "hStatusBar": 40,
            "fixedX": 65,
            "fixedY": 238,
            "isUIScreen": true,
            "isUIElement": true,
            "hasChildren": true,
            "isContainer": true,
            "textTitle": "Text",
            "isRect": true,
            "style": {
                "lineWidth": 2,
                "lineColor": "Green",
                "fillColor": "white",
                "textColor": "Black",
                "fontSize": 24,
                "fontFamily": "serif"
            },
            "events": {
                "onClick": "console.log(\"onClick was triggered\")"
            },
            "images": {
                "display": 2
            },
            "children": [
                {
                    "type": "ui-status-bar",
                    "name": "ui-status-bar",
                    "w": 640,
                    "h": 40,
                    "x": 0,
                    "y": 0,
                    "text": "",
                    "scale": 1,
                    "userMovable": false,
                    "userResizable": false,
                    "textType": 0,
                    "vAlign": "middle",
                    "hAlign": "center",
                    "defWidth": 640,
                    "defHeight": 40,
                    "rectSelectable": true,
                    "enable": true,
                    "visible": true,
                    "opacity": 1,
                    "vMargin": 0,
                    "hMargin": 0,
                    "xAttr": 0,
                    "yAttr": 0,
                    "widthAttr": 2,
                    "heightAttr": 0,
                    "needRelayout": true,
                    "xParam": 1,
                    "yParam": 1,
                    "widthParam": 1,
                    "heightParam": 1,
                    "isUIStatusBar": true,
                    "isUIElement": true,
                    "hasChildren": true,
                    "isContainer": true,
                    "textTitle": "Text",
                    "isRect": true,
                    "style": {
                        "lineWidth": 2,
                        "lineColor": "Green",
                        "fillColor": "white",
                        "textColor": "Black",
                        "fontSize": 24,
                        "fontFamily": "serif"
                    },
                    "events": {
                        "onClick": "console.log(\"onClick was triggered\")"
                    },
                    "images": {
                        "display": 3,
                        "default_bg": "drawapp8\/images\/theme\/default\/iphone\/5\/status_bar.png"
                    }
                },
                {
                    "type": "ui-window-manager",
                    "name": "window-manager",
                    "w": 640,
                    "h": 1096,
                    "x": 0,
                    "y": 40,
                    "text": "",
                    "scale": 1,
                    "userMovable": false,
                    "userResizable": false,
                    "textType": 0,
                    "vAlign": "middle",
                    "hAlign": "center",
                    "defWidth": 200,
                    "defHeight": 200,
                    "rectSelectable": true,
                    "enable": true,
                    "visible": true,
                    "opacity": 1,
                    "vMargin": 0,
                    "hMargin": 0,
                    "xAttr": 0,
                    "yAttr": 0,
                    "widthAttr": 2,
                    "heightAttr": 0,
                    "current": 0,
                    "needRelayout": true,
                    "xParam": 1,
                    "yParam": 1,
                    "widthParam": 1,
                    "heightParam": 1,
                    "isUIWindowManager": true,
                    "isUIFrames": true,
                    "isUIElement": true,
                    "hasChildren": true,
                    "isContainer": true,
                    "textTitle": "Text",
                    "isRect": true,
                    "showHignlight": false,
                    "style": {
                        "lineWidth": 2,
                        "lineColor": "Green",
                        "fillColor": "white",
                        "textColor": "Black",
                        "fontSize": 24,
                        "fontFamily": "serif"
                    },
                    "events": {
                        "onClick": "console.log(\"onClick was triggered\")",
                        "onChanged": null
                    },
                    "images": {
                        "display": 2
                    },
                    "children": [
                        {
                            "type": "ui-window",
                            "name": "win-main",
                            "w": 640,
                            "h": 1096,
                            "x": 0,
                            "y": 0,
                            "text": "",
                            "scale": 1,
                            "userMovable": true,
                            "userResizable": true,
                            "textType": 0,
                            "vAlign": "middle",
                            "hAlign": "center",
                            "defWidth": 480,
                            "defHeight": 760,
                            "rectSelectable": true,
                            "enable": true,
                            "visible": true,
                            "opacity": 1,
                            "vMargin": 0,
                            "hMargin": 0,
                            "xAttr": 0,
                            "yAttr": 0,
                            "widthAttr": 2,
                            "heightAttr": 2,
                            "animHint": "htranslate",
                            "needRelayout": true,
                            "xParam": 1,
                            "yParam": 1,
                            "widthParam": 1,
                            "heightParam": 1,
                            "isUINormalWindow": true,
                            "isUIWindow": true,
                            "isUIElement": true,
                            "hasChildren": true,
                            "isContainer": true,
                            "textTitle": "Text",
                            "isRect": true,
                            "style": {
                                "lineWidth": 2,
                                "lineColor": "Green",
                                "fillColor": "#f5f5f5",
                                "textColor": "Black",
                                "fontSize": 24,
                                "fontFamily": "serif"
                            },
                            "events": {
                                "onClick": "console.log(\"onClick was triggered\")",
                                "onLoad": "console.log(\"onLoad was triggered\")",
                                "onUnload": "console.log(\"onUnload was triggered\")",
                                "onOpen": null,
                                "onBeforeOpen": null,
                                "onClose": null,
                                "onSwithToBack": null,
                                "onSwithToFront": null,
                                "onGesture": "console.log(\"onGesture was triggered\")",
                                "onKeyDown": null,
                                "onKeyUp": null
                            },
                            "images": {
                                "display": 2
                            },
                            "children": [
                                {
                                    "type": "ui-image",
                                    "name": "ui-image",
                                    "w": 200,
                                    "h": 200,
                                    "x": 0,
                                    "y": 0,
                                    "text": "",
                                    "scale": 1,
                                    "userMovable": true,
                                    "userResizable": true,
                                    "textType": 0,
                                    "vAlign": "middle",
                                    "hAlign": "center",
                                    "defWidth": 200,
                                    "defHeight": 200,
                                    "rectSelectable": true,
                                    "enable": true,
                                    "visible": true,
                                    "opacity": 1,
                                    "vMargin": 0,
                                    "hMargin": 0,
                                    "xAttr": 2,
                                    "yAttr": 4,
                                    "widthAttr": 0,
                                    "heightAttr": 0,
                                    "clickable": false,
                                    "imageRotation": 0,
                                    "clickedStyleParam": 0.8,
                                    "clickedStyleType": 0,
                                    "needRelayout": true,
                                    "xParam": 0,
                                    "yParam": 1,
                                    "widthParam": 1,
                                    "heightParam": 1,
                                    "isUIImage": true,
                                    "isUIElement": true,
                                    "hasChildren": true,
                                    "isContainer": true,
                                    "textTitle": "Text",
                                    "isRect": true,
                                    "style": {
                                        "lineWidth": 2,
                                        "lineColor": "Red",
                                        "fillColor": "White",
                                        "textColor": "Black",
                                        "fontSize": 24,
                                        "fontFamily": "serif"
                                    },
                                    "events": {
                                        "onClick": null
                                    },
                                    "images": {
                                        "display": 0,
                                        "default_bg": "drawapp8\/images\/common\/default_image.png"
                                    }
                                },
                                {
                                    "type": "ui-image",
                                    "name": "ui-image",
                                    "w": 200,
                                    "h": 200,
                                    "x": 440,
                                    "y": 896,
                                    "text": "",
                                    "scale": 1,
                                    "userMovable": true,
                                    "userResizable": true,
                                    "textType": 0,
                                    "vAlign": "middle",
                                    "hAlign": "center",
                                    "defWidth": 200,
                                    "defHeight": 200,
                                    "rectSelectable": true,
                                    "enable": true,
                                    "visible": true,
                                    "opacity": 1,
                                    "vMargin": 0,
                                    "hMargin": 0,
                                    "xAttr": 2,
                                    "yAttr": 5,
                                    "widthAttr": 0,
                                    "heightAttr": 0,
                                    "clickable": false,
                                    "imageRotation": 0,
                                    "clickedStyleParam": 0.8,
                                    "clickedStyleType": 0,
                                    "needRelayout": true,
                                    "xParam": 0.6875,
                                    "yParam": 1,
                                    "widthParam": 1,
                                    "heightParam": 1,
                                    "isUIImage": true,
                                    "isUIElement": true,
                                    "hasChildren": true,
                                    "isContainer": true,
                                    "textTitle": "Text",
                                    "isRect": true,
                                    "style": {
                                        "lineWidth": 2,
                                        "lineColor": "Red",
                                        "fillColor": "White",
                                        "textColor": "Black",
                                        "fontSize": 24,
                                        "fontFamily": "serif"
                                    },
                                    "events": {
                                        "onClick": null
                                    },
                                    "images": {
                                        "display": 0,
                                        "default_bg": "drawapp8\/images\/common\/default_image.png"
                                    }
                                },
                                {
                                    "type": "ui-button",
                                    "name": "ui-button",
                                    "w": 208,
                                    "h": 98,
                                    "x": 216,
                                    "y": 0,
                                    "text": "Close",
                                    "scale": 1,
                                    "userMovable": true,
                                    "userResizable": true,
                                    "textType": 1,
                                    "vAlign": "middle",
                                    "hAlign": "center",
                                    "defWidth": 120,
                                    "defHeight": 60,
                                    "rectSelectable": true,
                                    "enable": true,
                                    "visible": true,
                                    "opacity": 1,
                                    "vMargin": 0,
                                    "hMargin": 0,
                                    "xAttr": 3,
                                    "yAttr": 4,
                                    "widthAttr": 0,
                                    "heightAttr": 0,
                                    "wMin": 50,
                                    "hMin": 50,
                                    "enableAutoScaleFontSize": true,
                                    "xParam": 1,
                                    "yParam": 1,
                                    "widthParam": 1,
                                    "heightParam": 1,
                                    "textY": 37.5,
                                    "textBaseline": "middle",
                                    "textX": 79.5,
                                    "textAlign": "center",
                                    "isUIButton": true,
                                    "isUIElement": true,
                                    "hasChildren": true,
                                    "isContainer": true,
                                    "textTitle": "Text",
                                    "isRect": true,
                                    "editing": false,
                                    "linkTo": "win:\/\/_prev_win_",
                                    "style": {
                                        "lineWidth": 2,
                                        "lineColor": "Red",
                                        "fillColor": "White",
                                        "textColor": "#E0E0E0",
                                        "fontSize": 28,
                                        "fontFamily": "serif",
                                        "textB": true,
                                        "enableGradient": true
                                    },
                                    "events": {
                                        "onClick": "var retCode = 0;\nthis.closeWindow(retCode);"
                                    },
                                    "images": {
                                        "display": 2,
                                        "focused_bg": "drawapp8\/images\/common\/icons\/xhdpi\/button_blue.9.png",
                                        "active_bg": "drawapp8\/images\/common\/icons\/xhdpi\/button_blue_active.9.png",
                                        "normal_bg": "drawapp8\/images\/common\/icons\/xhdpi\/button_blue.9.png",
                                        "disable_bg": "drawapp8\/images\/common\/icons\/xhdpi\/button_blue.9.png"
                                    }
                                },
                                {
                                    "type": "ui-image-animation",
                                    "name": "ui-image-animation",
                                    "w": 640,
                                    "h": 489,
                                    "x": 0,
                                    "y": 607,
                                    "text": "",
                                    "scale": 1,
                                    "userMovable": true,
                                    "userResizable": true,
                                    "textType": 0,
                                    "vAlign": "middle",
                                    "hAlign": "center",
                                    "defWidth": 640,
                                    "defHeight": 489,
                                    "rectSelectable": true,
                                    "enable": true,
                                    "visible": true,
                                    "opacity": 1,
                                    "vMargin": 0,
                                    "hMargin": 0,
                                    "xAttr": 0,
                                    "yAttr": 5,
                                    "widthAttr": 2,
                                    "heightAttr": 0,
                                    "xParam": 1,
                                    "yParam": 1,
                                    "widthParam": 1,
                                    "heightParam": 1,
                                    "frameRate": 6,
                                    "isUIImageAnimation": true,
                                    "isUIImageView": true,
                                    "isUIElement": true,
                                    "hasChildren": true,
                                    "isContainer": true,
                                    "textTitle": "Text",
                                    "isRect": true,
                                    "style": {
                                        "lineWidth": 2,
                                        "lineColor": "Orange",
                                        "fillColor": "White",
                                        "textColor": "Blue",
                                        "fontSize": 24,
                                        "fontFamily": "serif"
                                    },
                                    "events": {
                                        "onClick": null,
                                        "onChanged": null
                                    },
                                    "images": {
                                        "display": 4,
                                        "image_1": "images\/demos\/a0.jpg",
                                        "image_2": "images\/demos\/a1.jpg",
                                        "image_3": "images\/demos\/a2.jpg",
                                        "image_4": "images\/demos\/a3.jpg",
                                        "image_5": "images\/demos\/a4.jpg",
                                        "image_6": "images\/demos\/a5.jpg"
                                    },
                                    "userImages": "\/images\/demos\/a0.jpg\n\/images\/demos\/a1.jpg\n\/images\/demos\/a2.jpg\n\/images\/demos\/a3.jpg\n\/images\/demos\/a4.jpg\n\/images\/demos\/a5.jpg\n"
                                },
                                {
                                    "type": "ui-button",
                                    "name": "ui-button",
                                    "w": 120,
                                    "h": 60,
                                    "x": 160,
                                    "y": 234,
                                    "text": "Dialog",
                                    "scale": 1,
                                    "userMovable": true,
                                    "userResizable": true,
                                    "textType": 1,
                                    "vAlign": "middle",
                                    "hAlign": "center",
                                    "defWidth": 120,
                                    "defHeight": 60,
                                    "rectSelectable": true,
                                    "enable": true,
                                    "visible": true,
                                    "opacity": 1,
                                    "vMargin": 0,
                                    "hMargin": 0,
                                    "xAttr": 0,
                                    "yAttr": 0,
                                    "widthAttr": 0,
                                    "heightAttr": 0,
                                    "wMin": 50,
                                    "hMin": 50,
                                    "enableAutoScaleFontSize": true,
                                    "xParam": 1,
                                    "yParam": 1,
                                    "widthParam": 1,
                                    "heightParam": 1,
                                    "textY": 37.5,
                                    "textBaseline": "middle",
                                    "textX": 79.5,
                                    "textAlign": "center",
                                    "isUIButton": true,
                                    "isUIElement": true,
                                    "hasChildren": true,
                                    "isContainer": true,
                                    "textTitle": "Text",
                                    "isRect": true,
                                    "linkTo": "win:\/\/win-no-name2",
                                    "editing": false,
                                    "style": {
                                        "lineWidth": 2,
                                        "lineColor": "Red",
                                        "fillColor": "White",
                                        "textColor": "#E0E0E0",
                                        "fontSize": 28,
                                        "fontFamily": "serif",
                                        "textB": true,
                                        "enableGradient": true
                                    },
                                    "events": {
                                        "onClick": "this.openWindow(\"win-no-name2\", \n\tfunction (retCode) {console.log(\"window closed.\");});"
                                    },
                                    "images": {
                                        "display": 2,
                                        "focused_bg": "drawapp8\/images\/common\/icons\/xhdpi\/btn_2.9.png",
                                        "active_bg": "drawapp8\/images\/common\/icons\/xhdpi\/btn_2_pressed.9.png",
                                        "normal_bg": "drawapp8\/images\/common\/icons\/xhdpi\/btn_2.9.png",
                                        "disable_bg": "drawapp8\/images\/common\/icons\/xhdpi\/btn_2.9.png"
                                    }
                                },
                                {
                                    "type": "ui-button",
                                    "name": "ui-button",
                                    "w": 208,
                                    "h": 98,
                                    "x": 432,
                                    "y": 0,
                                    "text": "Open",
                                    "scale": 1,
                                    "userMovable": true,
                                    "userResizable": true,
                                    "textType": 1,
                                    "vAlign": "middle",
                                    "hAlign": "center",
                                    "defWidth": 120,
                                    "defHeight": 60,
                                    "rectSelectable": true,
                                    "enable": true,
                                    "visible": true,
                                    "opacity": 1,
                                    "vMargin": 0,
                                    "hMargin": 0,
                                    "xAttr": 5,
                                    "yAttr": 4,
                                    "widthAttr": 0,
                                    "heightAttr": 0,
                                    "wMin": 50,
                                    "hMin": 50,
                                    "enableAutoScaleFontSize": true,
                                    "xParam": 1,
                                    "yParam": 1,
                                    "widthParam": 1,
                                    "heightParam": 1,
                                    "textY": 37.5,
                                    "textBaseline": "middle",
                                    "textX": 79.5,
                                    "textAlign": "center",
                                    "isUIButton": true,
                                    "isUIElement": true,
                                    "hasChildren": true,
                                    "isContainer": true,
                                    "textTitle": "Text",
                                    "isRect": true,
                                    "editing": false,
                                    "linkTo": "win:\/\/win-no-name",
                                    "style": {
                                        "lineWidth": 2,
                                        "lineColor": "Red",
                                        "fillColor": "White",
                                        "textColor": "#E0E0E0",
                                        "fontSize": 28,
                                        "fontFamily": "serif",
                                        "textB": true,
                                        "enableGradient": true
                                    },
                                    "events": {
                                        "onClick": "this.openWindow(\"win-no-name\", \n\tfunction (retCode) {console.log(\"window closed.\");});"
                                    },
                                    "images": {
                                        "display": 2,
                                        "focused_bg": "drawapp8\/images\/common\/icons\/xhdpi\/button_red.9.png",
                                        "active_bg": "drawapp8\/images\/common\/icons\/xhdpi\/button_red_active.9.png",
                                        "normal_bg": "drawapp8\/images\/common\/icons\/xhdpi\/button_red.9.png",
                                        "disable_bg": "drawapp8\/images\/common\/icons\/xhdpi\/button_red.9.png"
                                    }
                                }
                            ]
                        },
                        {
                            "type": "ui-window",
                            "name": "win-no-name",
                            "w": 640,
                            "h": 1096,
                            "x": 0,
                            "y": 0,
                            "text": "",
                            "scale": 1,
                            "userMovable": true,
                            "userResizable": true,
                            "textType": 0,
                            "vAlign": "middle",
                            "hAlign": "center",
                            "defWidth": 640,
                            "defHeight": 920,
                            "rectSelectable": true,
                            "enable": true,
                            "visible": true,
                            "opacity": 1,
                            "vMargin": 0,
                            "hMargin": 0,
                            "xAttr": 0,
                            "yAttr": 0,
                            "widthAttr": 2,
                            "heightAttr": 2,
                            "animHint": "default",
                            "needRelayout": true,
                            "xParam": 1,
                            "yParam": 1,
                            "widthParam": 1,
                            "heightParam": 1,
                            "isUINormalWindow": true,
                            "isUIWindow": true,
                            "isUIElement": true,
                            "hasChildren": true,
                            "isContainer": true,
                            "textTitle": "Text",
                            "isRect": true,
                            "style": {
                                "lineWidth": 2,
                                "lineColor": "Green",
                                "fillColor": "White",
                                "textColor": "Black",
                                "fontSize": 24,
                                "fontFamily": "serif"
                            },
                            "events": {
                                "onClick": null,
                                "onLoad": null,
                                "onUnload": null,
                                "onOpen": "console.log(\"onOpen was triggered\")",
                                "onBeforeOpen": null,
                                "onClose": "console.log(\"onClose was triggered\")",
                                "onSwithToBack": null,
                                "onSwithToFront": null,
                                "onGesture": null,
                                "onKeyDown": null,
                                "onKeyUp": null
                            },
                            "images": {
                                "display": 2
                            },
                            "children": [
                                {
                                    "type": "ui-image-animation",
                                    "name": "ui-image-animation",
                                    "w": 640,
                                    "h": 489,
                                    "x": 0,
                                    "y": 194,
                                    "text": "",
                                    "scale": 1,
                                    "userMovable": true,
                                    "userResizable": true,
                                    "textType": 0,
                                    "vAlign": "middle",
                                    "hAlign": "center",
                                    "defWidth": 640,
                                    "defHeight": 489,
                                    "rectSelectable": true,
                                    "enable": true,
                                    "visible": true,
                                    "opacity": 1,
                                    "vMargin": 0,
                                    "hMargin": 0,
                                    "xAttr": 0,
                                    "yAttr": 0,
                                    "widthAttr": 2,
                                    "heightAttr": 0,
                                    "xParam": 1,
                                    "yParam": 1,
                                    "widthParam": 1,
                                    "heightParam": 1,
                                    "frameRate": 6,
                                    "isUIImageAnimation": true,
                                    "isUIImageView": true,
                                    "isUIElement": true,
                                    "hasChildren": true,
                                    "isContainer": true,
                                    "textTitle": "Text",
                                    "isRect": true,
                                    "style": {
                                        "lineWidth": 2,
                                        "lineColor": "Orange",
                                        "fillColor": "White",
                                        "textColor": "Blue",
                                        "fontSize": 24,
                                        "fontFamily": "serif"
                                    },
                                    "events": {
                                        "onClick": null,
                                        "onChanged": null
                                    },
                                    "images": {
                                        "display": 4,
                                        "image_1": "images\/demos\/a0.jpg",
                                        "image_2": "images\/demos\/a1.jpg",
                                        "image_3": "images\/demos\/a2.jpg",
                                        "image_4": "images\/demos\/a3.jpg",
                                        "image_5": "images\/demos\/a4.jpg",
                                        "image_6": "images\/demos\/a5.jpg"
                                    },
                                    "userImages": "\/images\/demos\/a0.jpg\n\/images\/demos\/a1.jpg\n\/images\/demos\/a2.jpg\n\/images\/demos\/a3.jpg\n\/images\/demos\/a4.jpg\n\/images\/demos\/a5.jpg\n"
                                },
                                {
                                    "type": "ui-button",
                                    "name": "ui-button",
                                    "w": 120,
                                    "h": 60,
                                    "x": 284,
                                    "y": 30,
                                    "text": "Close",
                                    "scale": 1,
                                    "userMovable": true,
                                    "userResizable": true,
                                    "textType": 1,
                                    "vAlign": "middle",
                                    "hAlign": "center",
                                    "defWidth": 120,
                                    "defHeight": 60,
                                    "rectSelectable": true,
                                    "enable": true,
                                    "visible": true,
                                    "opacity": 1,
                                    "vMargin": 0,
                                    "hMargin": 0,
                                    "xAttr": 0,
                                    "yAttr": 0,
                                    "widthAttr": 0,
                                    "heightAttr": 0,
                                    "wMin": 50,
                                    "hMin": 50,
                                    "enableAutoScaleFontSize": true,
                                    "needRelayout": true,
                                    "xParam": 1,
                                    "yParam": 1,
                                    "widthParam": 1,
                                    "heightParam": 1,
                                    "textY": 30,
                                    "textBaseline": "middle",
                                    "textX": 60,
                                    "textAlign": "center",
                                    "isUIButton": true,
                                    "isUIElement": true,
                                    "hasChildren": true,
                                    "isContainer": true,
                                    "textTitle": "Text",
                                    "isRect": true,
                                    "linkTo": "win:\/\/_prev_win_",
                                    "editing": false,
                                    "style": {
                                        "lineWidth": 2,
                                        "lineColor": "Red",
                                        "fillColor": "White",
                                        "textColor": "#E0E0E0",
                                        "fontSize": 28,
                                        "fontFamily": "serif",
                                        "textB": true
                                    },
                                    "events": {
                                        "onClick": "var retCode = 0;\nthis.closeWindow(retCode);"
                                    },
                                    "images": {
                                        "display": 2,
                                        "focused_bg": "drawapp8\/images\/theme\/default\/iphone\/button_focused.9.png",
                                        "active_bg": "drawapp8\/images\/theme\/default\/iphone\/button_active.9.png",
                                        "normal_bg": "drawapp8\/images\/theme\/default\/iphone\/button_normal.9.png",
                                        "disable_bg": "drawapp8\/images\/theme\/default\/iphone\/button_disable.9.png"
                                    }
                                }
                            ]
                        },
                        {
                            "type": "ui-dialog",
                            "name": "win-no-name2",
                            "w": 640,
                            "h": 400,
                            "x": 0,
                            "y": 348,
                            "text": "",
                            "scale": 1,
                            "userMovable": true,
                            "userResizable": true,
                            "textType": 0,
                            "vAlign": "middle",
                            "hAlign": "center",
                            "defWidth": 640,
                            "defHeight": 400,
                            "rectSelectable": true,
                            "enable": true,
                            "visible": true,
                            "opacity": 1,
                            "vMargin": 8,
                            "hMargin": 8,
                            "xAttr": 3,
                            "yAttr": 3,
                            "widthAttr": 2,
                            "heightAttr": 0,
                            "animHint": "scale",
                            "xParam": 1,
                            "yParam": 1,
                            "widthParam": 1,
                            "heightParam": 1,
                            "isUIDialog": true,
                            "isUIPopupWindow": true,
                            "isUIWindow": true,
                            "isUIElement": true,
                            "hasChildren": true,
                            "isContainer": true,
                            "textTitle": "Text",
                            "isRect": true,
                            "style": {
                                "lineWidth": 2,
                                "lineColor": "Green",
                                "fillColor": "white",
                                "textColor": "Black",
                                "fontSize": 24,
                                "fontFamily": "serif",
                                "enableGradient": true
                            },
                            "events": {
                                "onClick": null,
                                "onLoad": null,
                                "onUnload": null,
                                "onOpen": "console.log(\"onOpen was triggered\")",
                                "onBeforeOpen": null,
                                "onClose": "console.log(\"onClose was triggered\")",
                                "onSwithToBack": null,
                                "onSwithToFront": null,
                                "onGesture": "console.log(\"onGesture was triggered\")",
                                "onKeyDown": null,
                                "onKeyUp": null
                            },
                            "images": {
                                "display": 2,
                                "default_bg": "drawapp8\/images\/common\/icons\/dialog_bg_light.9.png"
                            },
                            "children": [
                                {
                                    "type": "ui-label",
                                    "name": "ui-label",
                                    "w": 624,
                                    "h": 40,
                                    "x": 8,
                                    "y": 130,
                                    "text": "Are sure quit without save?",
                                    "scale": 1,
                                    "userMovable": true,
                                    "userResizable": true,
                                    "textType": 2,
                                    "vAlign": "middle",
                                    "hAlign": "center",
                                    "defWidth": 200,
                                    "defHeight": 200,
                                    "rectSelectable": true,
                                    "enable": true,
                                    "visible": true,
                                    "opacity": 1,
                                    "vMargin": 0,
                                    "hMargin": 0,
                                    "xAttr": 3,
                                    "yAttr": 2,
                                    "widthAttr": 2,
                                    "heightAttr": 0,
                                    "autoAdjustHeight": false,
                                    "xParam": 1,
                                    "yParam": 0.33854166666667,
                                    "widthParam": 1,
                                    "heightParam": 1,
                                    "textY": 20,
                                    "textBaseline": "middle",
                                    "textX": 312,
                                    "textAlign": "center",
                                    "isUILabel": true,
                                    "isUIElement": true,
                                    "hasChildren": true,
                                    "isContainer": true,
                                    "textTitle": "Text",
                                    "isRect": true,
                                    "ANIM_OLD_OUT": 1,
                                    "ANIM_NEW_IN": 3,
                                    "style": {
                                        "lineWidth": 2,
                                        "lineColor": "Green",
                                        "fillColor": "white",
                                        "textColor": "#212121",
                                        "fontSize": 24,
                                        "fontFamily": "serif",
                                        "enableGradient": true
                                    },
                                    "events": {
                                        "onClick": null,
                                        "onChanged": null
                                    },
                                    "images": {
                                        "display": 2
                                    }
                                },
                                {
                                    "type": "ui-button",
                                    "name": "ui-button",
                                    "w": 187,
                                    "h": 80,
                                    "x": 84,
                                    "y": 256,
                                    "text": "Yes",
                                    "scale": 1,
                                    "userMovable": true,
                                    "userResizable": true,
                                    "textType": 1,
                                    "vAlign": "middle",
                                    "hAlign": "center",
                                    "defWidth": 120,
                                    "defHeight": 60,
                                    "rectSelectable": true,
                                    "enable": true,
                                    "visible": true,
                                    "opacity": 1,
                                    "vMargin": 0,
                                    "hMargin": 0,
                                    "xAttr": 2,
                                    "yAttr": 2,
                                    "widthAttr": 1,
                                    "heightAttr": 0,
                                    "wMin": 50,
                                    "hMin": 50,
                                    "enableAutoScaleFontSize": true,
                                    "xParam": 0.13461538461538,
                                    "yParam": 0.66666666666667,
                                    "widthParam": 0.29967948717949,
                                    "heightParam": 1,
                                    "textY": 40,
                                    "textBaseline": "middle",
                                    "textX": 93.5,
                                    "textAlign": "center",
                                    "isUIButton": true,
                                    "isUIElement": true,
                                    "hasChildren": true,
                                    "isContainer": true,
                                    "textTitle": "Text",
                                    "isRect": true,
                                    "widthScaleMin": 88,
                                    "widthScaleMax": 352,
                                    "style": {
                                        "lineWidth": 2,
                                        "lineColor": "Green",
                                        "fillColor": "#dcdcdc",
                                        "textColor": "#383838",
                                        "fontSize": 28,
                                        "fontFamily": "serif"
                                    },
                                    "events": {
                                        "onClick": "var retCode = 0;\nthis.closeWindow(retCode);"
                                    },
                                    "images": {
                                        "display": 2
                                    }
                                },
                                {
                                    "type": "ui-button",
                                    "name": "ui-button",
                                    "w": 187,
                                    "h": 80,
                                    "x": 365,
                                    "y": 256,
                                    "text": "No",
                                    "scale": 1,
                                    "userMovable": true,
                                    "userResizable": true,
                                    "textType": 1,
                                    "vAlign": "middle",
                                    "hAlign": "center",
                                    "defWidth": 120,
                                    "defHeight": 60,
                                    "rectSelectable": true,
                                    "enable": true,
                                    "visible": true,
                                    "opacity": 1,
                                    "vMargin": 0,
                                    "hMargin": 0,
                                    "xAttr": 2,
                                    "yAttr": 2,
                                    "widthAttr": 1,
                                    "heightAttr": 0,
                                    "wMin": 50,
                                    "hMin": 50,
                                    "enableAutoScaleFontSize": true,
                                    "xParam": 0.5849358974359,
                                    "yParam": 0.66666666666667,
                                    "widthParam": 0.29967948717949,
                                    "heightParam": 1,
                                    "textY": 40,
                                    "textBaseline": "middle",
                                    "textX": 93.5,
                                    "textAlign": "center",
                                    "isUIButton": true,
                                    "isUIElement": true,
                                    "hasChildren": true,
                                    "isContainer": true,
                                    "textTitle": "Text",
                                    "isRect": true,
                                    "widthScaleMin": 88,
                                    "widthScaleMax": 352,
                                    "editing": false,
                                    "style": {
                                        "lineWidth": 2,
                                        "lineColor": "Green",
                                        "fillColor": "#dcdcdc",
                                        "textColor": "#383838",
                                        "fontSize": 28,
                                        "fontFamily": "serif"
                                    },
                                    "events": {
                                        "onClick": "var retCode = 0;\nthis.closeWindow(retCode);"
                                    },
                                    "images": {
                                        "display": 2
                                    }
                                },
                                {
                                    "type": "ui-color-bar",
                                    "name": "ui-color-bar",
                                    "w": 505,
                                    "h": 64,
                                    "x": 68,
                                    "y": 213,
                                    "text": "",
                                    "scale": 1,
                                    "userMovable": true,
                                    "userResizable": true,
                                    "textType": 0,
                                    "vAlign": "middle",
                                    "hAlign": "center",
                                    "defWidth": 281,
                                    "defHeight": 56,
                                    "rectSelectable": false,
                                    "enable": true,
                                    "visible": true,
                                    "opacity": 1,
                                    "vMargin": 0,
                                    "hMargin": 0,
                                    "xAttr": 3,
                                    "yAttr": 2,
                                    "widthAttr": 1,
                                    "heightAttr": 0,
                                    "barPosition": 0,
                                    "barDierction": 0,
                                    "position": 0,
                                    "strColors": "#cccccc,#cccccc,#f5f5f5,#f5f5f5",
                                    "xParam": 1,
                                    "yParam": 0.5546875,
                                    "widthParam": 0.80929487179487,
                                    "heightParam": 1,
                                    "isUIColorBar": true,
                                    "isUIElement": true,
                                    "hasChildren": true,
                                    "isContainer": true,
                                    "textTitle": "Text",
                                    "isRect": true,
                                    "isUIButton": false,
                                    "widthScaleMin": 252,
                                    "widthScaleMax": 1010,
                                    "style": {
                                        "lineWidth": 2,
                                        "lineColor": "#dcdcdc",
                                        "fillColor": "#C0C0C0",
                                        "textColor": "Blue",
                                        "fontSize": 24,
                                        "fontFamily": "serif",
                                        "enableGradient": true
                                    },
                                    "events": {
                                        "onClick": null
                                    },
                                    "images": {
                                        "display": 2
                                    }
                                },
                                {
                                    "type": "ui-color-bar",
                                    "name": "ui-color-bar",
                                    "w": 87,
                                    "h": 93,
                                    "x": 277,
                                    "y": 268,
                                    "text": "",
                                    "scale": 1,
                                    "userMovable": true,
                                    "userResizable": true,
                                    "textType": 0,
                                    "vAlign": "middle",
                                    "hAlign": "center",
                                    "defWidth": 90,
                                    "defHeight": 280,
                                    "rectSelectable": false,
                                    "enable": true,
                                    "visible": true,
                                    "opacity": 1,
                                    "vMargin": 0,
                                    "hMargin": 0,
                                    "xAttr": 3,
                                    "yAttr": 2,
                                    "widthAttr": 0,
                                    "heightAttr": 0,
                                    "barPosition": 0,
                                    "barDierction": 0,
                                    "position": 0,
                                    "strColors": "#cccccc,#cccccc,#f5f5f5,#f5f5f5",
                                    "xParam": 1,
                                    "yParam": 0.69791666666667,
                                    "widthParam": 1,
                                    "heightParam": 1,
                                    "isUIColorBar": true,
                                    "isUIElement": true,
                                    "hasChildren": true,
                                    "isContainer": true,
                                    "textTitle": "Text",
                                    "isRect": true,
                                    "isUIButton": false,
                                    "barDirection": 1,
                                    "style": {
                                        "lineWidth": 2,
                                        "lineColor": "#dcdcdc",
                                        "fillColor": "#C0C0C0",
                                        "textColor": "Blue",
                                        "fontSize": 24,
                                        "fontFamily": "serif",
                                        "enableGradient": true
                                    },
                                    "events": {
                                        "onClick": null
                                    },
                                    "images": {
                                        "display": 2
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    "type": "ui-menu-bar",
                    "name": "ui-menu-bar",
                    "w": 640,
                    "h": 96,
                    "x": 0,
                    "y": 0,
                    "text": "",
                    "scale": 1,
                    "userMovable": false,
                    "userResizable": false,
                    "textType": 0,
                    "vAlign": "middle",
                    "hAlign": "center",
                    "defWidth": 640,
                    "defHeight": 96,
                    "rectSelectable": true,
                    "enable": false,
                    "visible": false,
                    "opacity": 1,
                    "vMargin": 0,
                    "hMargin": 0,
                    "xAttr": 0,
                    "yAttr": 0,
                    "widthAttr": 2,
                    "heightAttr": 0,
                    "needRelayout": true,
                    "xParam": 1,
                    "yParam": 1,
                    "widthParam": 1,
                    "heightParam": 1,
                    "isUIStatusBar": true,
                    "isUIElement": true,
                    "hasChildren": true,
                    "isContainer": true,
                    "textTitle": "Text",
                    "isRect": true,
                    "hideSelectMark": true,
                    "style": {
                        "lineWidth": 2,
                        "lineColor": "Orange",
                        "fillColor": "White",
                        "textColor": "Blue",
                        "fontSize": 24,
                        "fontFamily": "serif"
                    },
                    "events": {
                        "onClick": "console.log(\"onClick was triggered\")"
                    },
                    "images": {
                        "display": 3,
                        "default_bg": "drawapp8\/images\/theme\/default\/iphone\/menu_bar.png"
                    },
                    "children": [
                        {
                            "type": "ui-button",
                            "name": "ui-button",
                            "w": 100,
                            "h": 60,
                            "x": 0,
                            "y": 18,
                            "text": "",
                            "scale": 1,
                            "userMovable": false,
                            "userResizable": true,
                            "textType": 0,
                            "vAlign": "middle",
                            "hAlign": "center",
                            "defWidth": 120,
                            "defHeight": 60,
                            "rectSelectable": true,
                            "enable": true,
                            "visible": true,
                            "opacity": 1,
                            "vMargin": 0,
                            "hMargin": 0,
                            "xAttr": 4,
                            "yAttr": 3,
                            "widthAttr": 1,
                            "heightAttr": 1,
                            "wMin": 50,
                            "hMin": 50,
                            "enableAutoScaleFontSize": true,
                            "hideSelectMark": true,
                            "needRelayout": true,
                            "xParam": 1,
                            "yParam": 1,
                            "widthParam": 0.15625,
                            "heightParam": 0.625,
                            "textY": 29.5,
                            "textBaseline": "middle",
                            "textX": 52,
                            "textAlign": "center",
                            "isUIButton": true,
                            "isUIElement": true,
                            "hasChildren": true,
                            "isContainer": true,
                            "textTitle": "Text",
                            "isRect": true,
                            "style": {
                                "lineWidth": 2,
                                "lineColor": "Red",
                                "fillColor": "White",
                                "textColor": "Black",
                                "fontSize": 24,
                                "fontFamily": "serif"
                            },
                            "events": {
                                "onClick": "var device = this.getDevice();\nif(device) {\n    var wm = device.getWindowManager();\n    if(wm) {\n        wm.closeCurrentWindow(null);\n    }\n}"
                            },
                            "images": {
                                "display": 0,
                                "focused_bg": "drawapp8\/images\/theme\/default\/iphone\/menu_bar_return.png",
                                "active_bg": "drawapp8\/images\/theme\/default\/iphone\/menu_bar_return_active.png",
                                "normal_bg": "drawapp8\/images\/theme\/default\/iphone\/menu_bar_return.png",
                                "disable_bg": "drawapp8\/images\/theme\/default\/iphone\/menu_bar_return.png"
                            }
                        },
                        {
                            "type": "ui-button",
                            "name": "ui-button",
                            "w": 100,
                            "h": 60,
                            "x": 270,
                            "y": 18,
                            "text": "",
                            "scale": 1,
                            "userMovable": false,
                            "userResizable": true,
                            "textType": 0,
                            "vAlign": "middle",
                            "hAlign": "center",
                            "defWidth": 120,
                            "defHeight": 60,
                            "rectSelectable": true,
                            "enable": true,
                            "visible": true,
                            "opacity": 1,
                            "vMargin": 0,
                            "hMargin": 0,
                            "xAttr": 3,
                            "yAttr": 3,
                            "widthAttr": 1,
                            "heightAttr": 1,
                            "wMin": 50,
                            "hMin": 50,
                            "enableAutoScaleFontSize": true,
                            "hideSelectMark": true,
                            "needRelayout": true,
                            "xParam": 1,
                            "yParam": 1,
                            "widthParam": 0.15625,
                            "heightParam": 0.625,
                            "textY": 29.5,
                            "textBaseline": "middle",
                            "textX": 52,
                            "textAlign": "center",
                            "isUIButton": true,
                            "isUIElement": true,
                            "hasChildren": true,
                            "isContainer": true,
                            "textTitle": "Text",
                            "isRect": true,
                            "style": {
                                "lineWidth": 2,
                                "lineColor": "Red",
                                "fillColor": "White",
                                "textColor": "Black",
                                "fontSize": 24,
                                "fontFamily": "serif"
                            },
                            "events": {
                                "onClick": "console.log(\"onClick was triggered\")"
                            },
                            "images": {
                                "display": 0,
                                "focused_bg": "drawapp8\/images\/theme\/default\/iphone\/menu_bar_home.png",
                                "active_bg": "drawapp8\/images\/theme\/default\/iphone\/menu_bar_home.png",
                                "normal_bg": "drawapp8\/images\/theme\/default\/iphone\/menu_bar_home.png",
                                "disable_bg": "drawapp8\/images\/theme\/default\/iphone\/menu_bar_home.png"
                            }
                        },
                        {
                            "type": "ui-button",
                            "name": "ui-button",
                            "w": 100,
                            "h": 57,
                            "x": 540,
                            "y": 19,
                            "text": "",
                            "scale": 1,
                            "userMovable": false,
                            "userResizable": true,
                            "textType": 0,
                            "vAlign": "middle",
                            "hAlign": "center",
                            "defWidth": 120,
                            "defHeight": 60,
                            "rectSelectable": true,
                            "enable": true,
                            "visible": true,
                            "opacity": 1,
                            "vMargin": 0,
                            "hMargin": 0,
                            "xAttr": 5,
                            "yAttr": 3,
                            "widthAttr": 1,
                            "heightAttr": 1,
                            "wMin": 50,
                            "hMin": 50,
                            "enableAutoScaleFontSize": true,
                            "hideSelectMark": true,
                            "needRelayout": true,
                            "xParam": 1,
                            "yParam": 1,
                            "widthParam": 0.15625,
                            "heightParam": 0.59375,
                            "textY": 29.5,
                            "textBaseline": "middle",
                            "textX": 52,
                            "textAlign": "center",
                            "isUIButton": true,
                            "isUIElement": true,
                            "hasChildren": true,
                            "isContainer": true,
                            "textTitle": "Text",
                            "isRect": true,
                            "style": {
                                "lineWidth": 2,
                                "lineColor": "Red",
                                "fillColor": "White",
                                "textColor": "Black",
                                "fontSize": 24,
                                "fontFamily": "serif"
                            },
                            "events": {
                                "onClick": "console.log(\"onClick was triggered\")"
                            },
                            "images": {
                                "display": 0,
                                "focused_bg": "drawapp8\/images\/theme\/default\/iphone\/menu_bar_apps.png",
                                "active_bg": "drawapp8\/images\/theme\/default\/iphone\/menu_bar_apps.png",
                                "normal_bg": "drawapp8\/images\/theme\/default\/iphone\/menu_bar_apps.png",
                                "disable_bg": "drawapp8\/images\/theme\/default\/iphone\/menu_bar_apps.png"
                            }
                        }
                    ]
                }
            ]
        },
        {
            "type": "ui-button",
            "name": "button-prev",
            "w": 160,
            "h": 54,
            "x": 65,
            "y": 179,
            "text": "\u524d\u4e00\u7a97\u53e3",
            "scale": 1,
            "userMovable": false,
            "userResizable": false,
            "textType": 1,
            "vAlign": "middle",
            "hAlign": "center",
            "defWidth": 120,
            "defHeight": 60,
            "rectSelectable": true,
            "enable": true,
            "visible": true,
            "opacity": 1,
            "vMargin": 0,
            "hMargin": 0,
            "xAttr": 0,
            "yAttr": 0,
            "widthAttr": 0,
            "heightAttr": 0,
            "wMin": 50,
            "hMin": 50,
            "enableAutoScaleFontSize": true,
            "needRelayout": true,
            "xParam": 1,
            "yParam": 1,
            "widthParam": 1,
            "heightParam": 1,
            "fixedX": 65,
            "fixedY": 179,
            "textY": 27,
            "textBaseline": "middle",
            "textX": 80,
            "textAlign": "center",
            "isUIButton": true,
            "isUIElement": true,
            "hasChildren": true,
            "isContainer": true,
            "textTitle": "Text",
            "isRect": true,
            "style": {
                "lineWidth": 2,
                "lineColor": "Green",
                "fillColor": "",
                "textColor": "Black",
                "fontSize": 16,
                "fontFamily": "serif"
            },
            "events": {
                "onClick": "console.log(\"onClick was triggered\")"
            },
            "images": {
                "display": 2,
                "focused_bg": "drawapp8\/images\/design_button_focused.9.png",
                "active_bg": "drawapp8\/images\/design_button_active.9.png",
                "normal_bg": "drawapp8\/images\/design_button_normal.9.png",
                "disable_bg": "drawapp8\/images\/design_button_normal.9.png"
            }
        },
        {
            "type": "ui-button",
            "name": "button-next",
            "w": 160,
            "h": 54,
            "x": 225,
            "y": 179,
            "text": "\u4e0b\u4e00\u7a97\u53e3",
            "scale": 1,
            "userMovable": false,
            "userResizable": false,
            "textType": 1,
            "vAlign": "middle",
            "hAlign": "center",
            "defWidth": 120,
            "defHeight": 60,
            "rectSelectable": true,
            "enable": true,
            "visible": true,
            "opacity": 1,
            "vMargin": 0,
            "hMargin": 0,
            "xAttr": 0,
            "yAttr": 0,
            "widthAttr": 0,
            "heightAttr": 0,
            "wMin": 50,
            "hMin": 50,
            "enableAutoScaleFontSize": true,
            "needRelayout": true,
            "xParam": 1,
            "yParam": 1,
            "widthParam": 1,
            "heightParam": 1,
            "fixedX": 278,
            "fixedY": 179,
            "textY": 27,
            "textBaseline": "middle",
            "textX": 80,
            "textAlign": "center",
            "isUIButton": true,
            "isUIElement": true,
            "hasChildren": true,
            "isContainer": true,
            "textTitle": "Text",
            "isRect": true,
            "style": {
                "lineWidth": 2,
                "lineColor": "Green",
                "fillColor": "",
                "textColor": "Black",
                "fontSize": 16,
                "fontFamily": "serif"
            },
            "events": {
                "onClick": "console.log(\"onClick was triggered\")"
            },
            "images": {
                "display": 2,
                "focused_bg": "drawapp8\/images\/design_button_focused.9.png",
                "active_bg": "drawapp8\/images\/design_button_active.9.png",
                "normal_bg": "drawapp8\/images\/design_button_normal.9.png",
                "disable_bg": "drawapp8\/images\/design_button_normal.9.png"
            }
        },
        {
            "type": "ui-button",
            "name": "button-direction",
            "w": 160,
            "h": 54,
            "x": 385,
            "y": 179,
            "text": "\u6a2a\u5c4f",
            "scale": 1,
            "userMovable": false,
            "userResizable": false,
            "textType": 1,
            "vAlign": "middle",
            "hAlign": "center",
            "defWidth": 120,
            "defHeight": 60,
            "rectSelectable": true,
            "enable": true,
            "visible": true,
            "opacity": 1,
            "vMargin": 0,
            "hMargin": 0,
            "xAttr": 0,
            "yAttr": 0,
            "widthAttr": 0,
            "heightAttr": 0,
            "wMin": 50,
            "hMin": 50,
            "enableAutoScaleFontSize": true,
            "needRelayout": true,
            "xParam": 1,
            "yParam": 1,
            "widthParam": 1,
            "heightParam": 1,
            "fixedX": 278,
            "fixedY": 179,
            "textY": 27,
            "textBaseline": "middle",
            "textX": 80,
            "textAlign": "center",
            "isUIButton": true,
            "isUIElement": true,
            "hasChildren": true,
            "isContainer": true,
            "textTitle": "Text",
            "isRect": true,
            "style": {
                "lineWidth": 2,
                "lineColor": "Green",
                "fillColor": "",
                "textColor": "Black",
                "fontSize": 16,
                "fontFamily": "serif"
            },
            "events": {
                "onClick": "console.log(\"onClick was triggered\")"
            },
            "images": {
                "display": 2,
                "focused_bg": "drawapp8\/images\/design_button_focused.9.png",
                "active_bg": "drawapp8\/images\/design_button_active.9.png",
                "normal_bg": "drawapp8\/images\/design_button_normal.9.png",
                "disable_bg": "drawapp8\/images\/design_button_normal.9.png"
            }
        },
        {
            "type": "ui-button",
            "name": "button-status",
            "w": 320,
            "h": 40,
            "x": 225,
            "y": 148,
            "text": "main-win(1\/1)",
            "scale": 1,
            "userMovable": false,
            "userResizable": false,
            "textType": 1,
            "vAlign": "middle",
            "hAlign": "center",
            "defWidth": 120,
            "defHeight": 60,
            "rectSelectable": true,
            "enable": true,
            "visible": true,
            "opacity": 1,
            "vMargin": 0,
            "hMargin": 0,
            "xAttr": 0,
            "yAttr": 0,
            "widthAttr": 0,
            "heightAttr": 0,
            "wMin": 50,
            "hMin": 50,
            "enableAutoScaleFontSize": true,
            "needRelayout": true,
            "xParam": 1,
            "yParam": 1,
            "widthParam": 1,
            "heightParam": 1,
            "fixedX": 225,
            "fixedY": 148,
            "textY": 20,
            "textBaseline": "middle",
            "textX": 160,
            "textAlign": "center",
            "isUIButton": true,
            "isUIElement": true,
            "hasChildren": true,
            "isContainer": true,
            "textTitle": "Text",
            "isRect": true,
            "style": {
                "lineWidth": 2,
                "lineColor": "Green",
                "fillColor": "",
                "textColor": "Orange",
                "fontSize": 18,
                "fontFamily": "serif"
            },
            "events": {
                "onClick": "console.log(\"onClick was triggered\")"
            },
            "images": {
                "display": 2
            }
        },
        {
            "type": "ui-button",
            "name": "button-preview",
            "w": 160,
            "h": 54,
            "x": 545,
            "y": 179,
            "text": "\u9884\u89c8",
            "scale": 1,
            "userMovable": false,
            "userResizable": false,
            "textType": 1,
            "vAlign": "middle",
            "hAlign": "center",
            "defWidth": 120,
            "defHeight": 60,
            "rectSelectable": true,
            "enable": true,
            "visible": true,
            "opacity": 1,
            "vMargin": 0,
            "hMargin": 0,
            "xAttr": 0,
            "yAttr": 0,
            "widthAttr": 0,
            "heightAttr": 0,
            "wMin": 50,
            "hMin": 50,
            "enableAutoScaleFontSize": true,
            "needRelayout": true,
            "xParam": 1,
            "yParam": 1,
            "widthParam": 1,
            "heightParam": 1,
            "isPreview": false,
            "fixedX": 491.66666666667,
            "fixedY": 179,
            "textY": 27,
            "textBaseline": "middle",
            "textX": 80,
            "textAlign": "center",
            "isUIButton": true,
            "isUIElement": true,
            "hasChildren": true,
            "isContainer": true,
            "textTitle": "Text",
            "isRect": true,
            "style": {
                "lineWidth": 2,
                "lineColor": "Green",
                "fillColor": "",
                "textColor": "Black",
                "fontSize": 16,
                "fontFamily": "serif"
            },
            "events": {
                "onClick": "console.log(\"onClick was triggered\")"
            },
            "images": {
                "display": 2,
                "focused_bg": "drawapp8\/images\/design_button_focused.9.png",
                "active_bg": "drawapp8\/images\/design_button_active.9.png",
                "normal_bg": "drawapp8\/images\/design_button_normal.9.png",
                "disable_bg": "drawapp8\/images\/design_button_normal.9.png"
            }
        }
    ],
    "meta": {
        "general": {
            "appid": "com.drawapp8.demo",
            "appversion": "1.0.0",
            "appname": "demo",
            "appdesc": "demo for drawapp8",
            "icon": "http:\/\/www.drawapp8.com\/drawapp8\/images\/common\/appicons\/32.png",
            "splash": "http:\/\/www.drawapp8.com\/drawapp8\/images\/common\/appsplash\/splash.png",
            "gapversion": "",
            "orientation": "portrait",
            "targetdevice": "universal",
            "fullscreen": false,
            "battery": false,
            "camera": false,
            "contacts": false,
            "file": true,
            "geolocation": false,
            "media": true,
            "network": true,
            "notification": true,
            "device": true
        },
        "ios": {
            "statusbarstyle": "default",
            "webviewbounce": false,
            "prerenderedicon": true,
            "stayinwebview": false,
            "detectdatatypes": false,
            "exitonsuspend": true,
            "showsplashscreenspinner": true,
            "autohidesplashscreen": true,
            "l_splashipad": "",
            "p_splashipad": "",
            "l_splashiphone5": "",
            "p_splashiphone5": "",
            "l_splashretina": "",
            "p_splashretina": "",
            "l_splashclassic": "",
            "p_splashclassic": "",
            "iconclassic": "icons\/ios\/icon.png",
            "iconretina": "icons\/ios\/icon_at_2x.png",
            "iconipad": "http:\/\/www.drawapp8.com\/drawapp8\/images\/common\/appicons\/114.png"
        },
        "webos": {
            "icondefault": "icons\/webos\/icon.png",
            "iconmini": "icons\/webos\/miniicon.png"
        },
        "firefoxos": {
            "icon30": "icons\/firefoxos\/icon30.png",
            "icon60": "icons\/firefoxos\/icon60.png",
            "icon128": "icons\/firefoxos\/icon128.png",
            "author_name": "drawapp8",
            "author_home_page": "http:\/\/www.drawapp8.com",
            "launch_path": "\/apps\/",
            "app_type": "web",
            "extra": ""
        },
        "android": {
            "installlocation": "auto",
            "iconldpi": "icons\/android\/ldpi.png",
            "iconmdpi": "icons\/android\/mdpi.png",
            "iconhdpi": "icons\/android\/hdpi.png",
            "iconxhdpi": "icons\/android\/xhdpi.png",
            "splashldpi": "",
            "splashmdpi": "",
            "splashhdpi": "",
            "splashxhdpi": ""
        },
        "blackberry": {
            "disablecursor": true,
            "iconhover": "icons\/bb\/icon_hover.png",
            "iconnhover": "icons\/bb\/icon.png",
            "splash": ""
        },
        "winphone": {
            "iconregular": "icons\/winphone\/icon.png",
            "icontile": "icons\/winphone\/tileicon.png",
            "splash": ""
        }
    }
};
